### ISSUE TITLE
Update style.css

### ISSUE THREAD

**Issue by LoubiTek** [hawkthorne/hawkthorne-costume#6]
https://github.com/LoubiTek/hawkthorne-costume/commit/3de5d5b600745948064d007aeb2a52443f6e37a7

**Comment by niamu** [comment]
I'm not sure what the benefit is of these minor style changes or what it fixes. And this was open as an issue so I'm assuming that something is wrong? At a glance I don't think there's anything here that fixes anything or improves anything greatly.

In the future please create pull requests with a detailed explanation and always open an issue first to talk about possible issues or enhancements so we can understand what is wrong.

**Comment by 8bitgentleman** [comment]
Does this costume tester even still work?

**Comment by niamu** [comment]
[Not really](http://hawkthorne-costume.herokuapp.com/chang/https%3A%2F%2Fraw.github.com%2Fhawkthorne%2Fhawkthorne-journey%2Fmaster%2Fsrc%2Fimages%2Fcharacters%2Fchang%2Fdictator.png).

There are many toggles that don't appear to do anything and I've never seen it in working order since I joined the project so I'm not even sure what it should be doing to fix it.

We don't have any public links to it anymore anyways. I don't think it will ever get fixed. We'll likely end up building a replacement at some point.

**Comment by 8bitgentleman** [comment]
I think @NimbusBP1729 might have built a replacement [here](http://nimbusbp1729.github.io/animator/), or at least fixed this to work with HTML5.
